import 'package:evira_e_commerce/features/customer_service/data/models/message_model.dart';
import 'package:evira_e_commerce/features/customer_service/domain/datasource/customer_service_remote_datasource.dart';
import 'package:evira_e_commerce/features/customer_service/domain/entities/message_entity.dart';
import 'package:evira_e_commerce/features/customer_service/domain/repo/customer_service_repo.dart';
import 'package:injectable/injectable.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

@LazySingleton(as: CustomerServiceRepo)
class CustomerServiceImpl implements CustomerServiceRepo {
  final supabase = Supabase.instance.client;
  final CustomerServiceRemoteDatasource _customerServiceRemoteDatasource;

  CustomerServiceImpl(this._customerServiceRemoteDatasource);

  @override
  Stream<List<MessageEntity>> getMessages() {
    return _customerServiceRemoteDatasource.getMessages().map(
      (messageModels) => messageModels
          .map(
            (model) => MessageEntity(
              id: model.id,
              content: model.content,
              createdAt: model.createdAt,
              isUserMessage: model.isUserMessage,
            ),
          )
          .toList(),
    );
  }

  @override
  Future<void> sendMessage({
    required String message,
    required bool isUserMessage,
  }) async {
    final messageModel = MessageModel(
      id: '', // ID is generated by Supabase
      content: message,
      createdAt: DateTime.now(),
      isUserMessage: isUserMessage,
    );

    print(message);

    return _customerServiceRemoteDatasource.sendMessage(
      messageModel: messageModel,
    );
  }
}
